### ISSUE TITLE
form/field.html.twig uses a tu filter which is not defined

### ISSUE THREAD

**Issue by hwmaier** [getgrav/grav-plugin-form#13]
What is the `tu` filter in "forms/field.html.twig" at line 48 supposed to do and where should it be defined? It looks like some hook for translation. Should this be just `t` for the Grav translation filter?

I am getting ` Twig_Error_Syntax - The filter "tu" does not exist in "forms/field.html.twig" at line 48 ` if i have set `twig: undefined_filters: false` in system.yaml.

**Comment by flaviocopes** [comment]
We use `tu` in the admin plugin, to use the langauge set in the user preferences (`tu` is an acronym for `translate user`). 

Since that part of the form plugin was migrated from the admin plugin, looks like a leftover. Committed a fix, can you check? https://github.com/getgrav/grav-plugin-form/commit/5f571111fbf73fab4aecddef5283c5e5a1925469

**Comment by hwmaier** [comment]
Your patch works once a semicolon is added to line 175 of form.php.

**Comment by flaviocopes** [comment]
Missed that from another commit! Fixed

**Comment by hwmaier** [comment]
All good now. Thanks for clarification and fix.
