### ISSUE TITLE
`form-styles.css` always loaded in front-end even when not used

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-form#248]
While playing around with the standard `core + admin` install, I noticed that `form-styles.css` is always loaded when displaying a front-end page without even using any forms.

I've also looked at the settings, but didn't see a setting to disable it for front-end pages.

Am I overseeing something or is this stylesheet really unnecessary?

**Comment by rhukster** [comment]
You can disable it via config:

https://github.com/getgrav/grav-plugin-form/blob/develop/form.php#L260-L262

It's not something we can dynamically add because you can inject forms in many ways including directly in page content, or via Twig.  If done via Twig for example, it's often too late in the lifecycle to add the CSS as output of the CSS files has already been done.
