### ISSUE TITLE
name="XXX" instead of name="data[XXX]"?

### ISSUE THREAD

**Issue by nclm** [getgrav/grav-plugin-form#559]
Hi,

I’m making a form that has a field like this:

```
        -
            type: text
            name: XXX
```

However, it is converted into this HTML:
```
<input name="data[XXX]" value="" type="text">
```

Instead of:
```
<input name="XXX" value="" type="text">
```

How do I make it `name="XXX"` and not `name="data[XXX]"`?

I’m sending the form through `POST` to an external service, so it is important for the field name not to be anything else.

Thanks!

**Comment by rhukster** [comment]
Perhaps @mahagr can better answer this, but from my knowledge, the `data[xxx]` syntax is just how Grav forms work. There are other internal form hidden inputs that are at the root of the form (nonce, remember-me, etc) and putting the  form data inside a specific `data[]` array ensures we can easily get to that data without having to manually strip out any other extraneous input fields.  So it's really just an internal thing so that Grav forms can function reliably. 

However, there's nothing stopping you from just creating a form manually in Twig, rather than using Grav forms for your definition. I've done that several times where I just need  a simple form that is being sent or processed by an external service (mailinglist signup for example).  You create it in the same HTML structure with the same CSS as a Grav form, so the styling matches.

**Comment by mahagr** [comment]
You can try setting `scope` in twig if you handle the data yourself.
